AWSTemplateFormatVersion: 2010-09-09
Description: ECR repo for trms lambda
Resources:
  TrmsECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: 'trms-lambda'
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only two untagged images, expire all others",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "imageCountMoreThan",
                  "countNumber": 2
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
Outputs:
  TrmsECRArn:
    Value: !GetAtt TrmsECR.Arn
    Export:
      Name: TrmsECRArn
